# File used for testing.

params:
  seed: ${...seed}

  algo:
    name: amp_continuous

  model:
    name: continuous_amp

  network:
    name: amp
    separate: True

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0.0 # HumanoidAMPPPO: -2.9
        fixed_sigma: True
        learn_sigma: False

    mlp:
      units: [1024, 512] # HumanoidAMPPPO: [1024, 512]
      activation: relu #  HumanoidAMPPPO: relu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

    disc:
      units: [256, 128, 64] # HumanoidAMPPPO: [1024, 512]
      activation: relu

      initializer:
        name: default

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:PunyoV2AMP_test,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    ppo: True
    multi_gpu: ${....multi_gpu}
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-5
    lr_schedule: constant # HumanoidAMPPPO: constant
    #schedule_type: standard # comment out if choose constant
    kl_threshold: 0.008
    score_to_win: 10000 # HumanoidAMPPPO: 20000
    max_epochs: ${resolve_default:1500,${....max_iterations}}
    save_best_after: 50
    save_frequency: 10
    print_stats: True
    # grad_norm: Applied if truncate_grads is True. Good value is in (1.0, 10.0).
    grad_norm: 1.0
    entropy_coef: 0.0
    # truncate_grads: Apply truncate grads or not. It stabilizes training.
    truncate_grads: False # HumanoidAMPPPO: False
    # e_clip: Clip parameter for ppo loss.
    e_clip: 0.2
    horizon_length: 64 # HumanoidAMPPPO: 16
    minibatch_size: 32768 # HumanoidAMPPPO: 32768
    mini_epochs: 6 # HumanoidAMPPPO: 6
    critic_coef: 5 # HumanoidAMPPPO: 5
    clip_value: False # HumanoidAMPPPO: False
    seq_len: 4
    bounds_loss_coef: 10 # HumanoidAMPPPO: 10
    amp_obs_demo_buffer_size: 200000
    amp_replay_buffer_size: 1000000
    amp_replay_keep_prob: 0.01
    amp_batch_size: 512
    amp_minibatch_size: 4096
    disc_coef: 5
    disc_logit_reg: 0.05
    disc_grad_penalty: 10
    disc_reward_scale: 1
    disc_weight_decay: 0.0001
    normalize_amp_input: True

    # disc_reward_w = 1 - task_reward_w is calculated in the code
    task_reward_w: 0.8

    curriculum: True
    curriculum_params:
      task_reward_w:
        start_at:  0
        stop_at: 200000
        frequency: 2000  # Define how many simulation steps between stepping the curriculum
        operation: "additive"
        value: 0.02
        direction: "increase"
